### ISSUE TITLE
Why are we disabling transactions explicitly?

### ISSUE THREAD

**Issue by sleberknight** [kiwiproject/dropwizard-mongo-migrations#14]
We currently disable transactions [here](https://github.com/kiwiproject/dropwizard-mongo-migrations/blob/2d9512bb361ee84fcc46993c09e3605a38697c4f/src/main/java/org/kiwiproject/migrations/mongo/AbstractMongockCommand.java#L32) in `AbstractMongockCommand#run`.

Should we change this, or at least provide a way to configure so that it leaves transactions enabled, e.g. in `MongoMigrationConfiguration`?

Probably need to better understand the implications of having transactions enabled vs. disabled when running Mongo migrations.

**Comment by chrisrohr** [comment]
We may want to make this configurable somehow.  The reason, albeit not a very good one, is that the unit tests fail if they are not disabled.  This is due to this error:

`com.mongodb.MongoClientException: Sessions are not supported by the MongoDB cluster to which this client is connected`

Now, while we should NOT be making production decisions based on the test, this could be a valid scenario where someone is using a cluster and transactions are not supported.  This is why I'm leaning towards making this configurable per the suggestion.

Last question would be what default to use?  To use transactions or not to use transactions, that is the question.

**Comment by chrisrohr** [comment]
I decided to make the default use transactions as I would think that would be the "normal" use-case
